# radius specifies the radius of the cube
radius: 64

# lower-limit-distance specifies the distance between the crystal and the lower border of the area
lower-limit-distance: 1

# set crystal-name to a value to make only renamed end crystals to be spawn proofing;
crafting-name: "mobproof"

